### ISSUE TITLE
LinkedIn Version 2 API requirements

### ISSUE THREAD

**Issue by morganm00** [wso2-extensions/identity-outbound-auth-linkedIn#12]
**Description:**
LinkedIn has published this update last December:
https://engineering.linkedin.com/blog/2018/12/developer-program-updates

According to the document, the v1 API will cease to function as of March 1, 2019.

Is there any update on this or is this expected to cause problems with this plugin?   Alternatively, is there another WSO2 IS "owned" plugin to support this?

**Affected Product Version:**
1.0.3

**Comment by robsonkades** [comment]
Hello @morganm00 
pull request with support new api version 
https://github.com/wso2-extensions/identity-outbound-auth-linkedIn/pull/13

**Comment by madurangasiriwardena** [comment]
Relates to https://github.com/wso2/product-is/issues/5953
